// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "One Tap SwiftUI",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "One Tap SwiftUI",
            targets: ["AppModule"],
            bundleIdentifier: "one.hdcola.onetapswiftui",
            teamIdentifier: "T4W3MN6QHA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "Use Location in Map View show case")
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/HDCodePractice/SwiftUITapsPackage", "1.0.4"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUITapsPackage", package: "SwiftUITapsPackage")
            ],
            path: "."
        )
    ]
)
